server:
  port: 8888
spring:
  security:
    user:
      name: secure_user
      password: secure_config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dev-praveen/central-config
          clone-on-start: true
          default-label: master